// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *book → Format*
 */
export interface BookDocumentDataFormatItem {
  /**
   * formaat field in *book → Format*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.format[].formaat
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  formaat: prismic.KeyTextField;
}

/**
 * Item in *book → Categories*
 */
export interface BookDocumentDataCategoriesItem {
  /**
   * category field in *book → Categories*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.categories[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;
}

type BookDocumentDataSlicesSlice = DetailsliceSlice;

/**
 * Content for book documents
 */
interface BookDocumentData {
  /**
   * title field in *book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * author field in *book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Description field in *book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * cover_url field in *book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book.cover_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cover_url: prismic.KeyTextField;

  /**
   * Format field in *book*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book.format[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  format: prismic.GroupField<Simplify<BookDocumentDataFormatItem>>;

  /**
   * Categories field in *book*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book.categories[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  categories: prismic.GroupField<Simplify<BookDocumentDataCategoriesItem>>;

  /**
   * Slice Zone field in *book*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: book.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BookDocumentDataSlicesSlice>;
}

/**
 * book document from Prismic
 *
 * - **API ID**: `book`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BookDocumentData>, "book", Lang>;

/**
 * Item in *Filternav → Format*
 */
export interface FilternavDocumentDataFormatItem {
  /**
   * item_label field in *Filternav → Format*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.format[].item_label
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_label: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Filternav → Themen*
 */
export interface FilternavDocumentDataThemenItem {
  /**
   * Titel field in *Filternav → Themen*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.themen[].titel
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titel: prismic.RichTextField;

  /**
   * Subtopic field in *Filternav → Themen*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.themen[].subtopic
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  subtopic: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Filternav documents
 */
interface FilternavDocumentData {
  /**
   * Format_heading field in *Filternav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.format_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  format_heading: prismic.RichTextField;

  /**
   * Format field in *Filternav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.format[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  format: prismic.GroupField<Simplify<FilternavDocumentDataFormatItem>>;

  /**
   * Themen_heading field in *Filternav*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.themen_heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  themen_heading: prismic.RichTextField;

  /**
   * Themen field in *Filternav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: filternav.themen[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  themen: prismic.GroupField<Simplify<FilternavDocumentDataThemenItem>>;
}

/**
 * Filternav document from Prismic
 *
 * - **API ID**: `filternav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FilternavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FilternavDocumentData>,
    "filternav",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | DetailSlice
  | ImpressumSlice
  | AboutSlice
  | WelcomeSlice
  | BookListSlice
  | FeaturesSlice
  | HeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Discription field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_discription
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_discription: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Searchresults → book*
 */
export interface SearchresultsDocumentDataBookItem {
  /**
   * title field in *Searchresults → book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.book[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * author field in *Searchresults → book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.book[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * cover_url field in *Searchresults → book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.book[].cover_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cover_url: prismic.KeyTextField;
}

type SearchresultsDocumentDataSlicesSlice = BookResultsSlice;

/**
 * Content for Searchresults documents
 */
interface SearchresultsDocumentData {
  /**
   * Heading  field in *Searchresults*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Formatzahl field in *Searchresults*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.formatzahl
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  formatzahl: prismic.RichTextField;

  /**
   * book field in *Searchresults*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.book[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  book: prismic.GroupField<Simplify<SearchresultsDocumentDataBookItem>>;

  /**
   * Slice Zone field in *Searchresults*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: searchresults.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SearchresultsDocumentDataSlicesSlice>;
}

/**
 * Searchresults document from Prismic
 *
 * - **API ID**: `searchresults`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SearchresultsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SearchresultsDocumentData>,
    "searchresults",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Discription field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_discription
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_discription: prismic.KeyTextField;

  /**
   * OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BookDocument
  | FilternavDocument
  | PageDocument
  | SearchresultsDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Links field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.links
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  links: prismic.RichTextField;

  /**
   * Person field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.person
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  person: prismic.ImageField<never>;

  /**
   * Rechts field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.rechts
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  rechts: prismic.RichTextField;

  /**
   * Logo field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *BookList → Default → Primary → Content*
 */
export interface BookListSliceDefaultPrimaryContentItem {
  /**
   * Cover image field in *BookList → Default → Primary → Content*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content[].cover_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Titel field in *BookList → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content[].titel
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  titel: prismic.RichTextField;

  /**
   * Author field in *BookList → Default → Primary → Content*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;
}

/**
 * Item in *BookList → Default → Primary → Content_2*
 */
export interface BookListSliceDefaultPrimaryContent2Item {
  /**
   * Cover image field in *BookList → Default → Primary → Content_2*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content_2[].cover_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Title field in *BookList → Default → Primary → Content_2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content_2[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Author field in *BookList → Default → Primary → Content_2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content_2[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;
}

/**
 * Primary content in *BookList → Default → Primary*
 */
export interface BookListSliceDefaultPrimary {
  /**
   * Heading field in *BookList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Heading_2 field in *BookList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading_2: prismic.RichTextField;

  /**
   * Content field in *BookList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  content: prismic.GroupField<Simplify<BookListSliceDefaultPrimaryContentItem>>;

  /**
   * Content_2 field in *BookList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.content_2[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  content_2: prismic.GroupField<
    Simplify<BookListSliceDefaultPrimaryContent2Item>
  >;

  /**
   * Mehr laden field in *BookList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_list.default.primary.mehr_laden
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  mehr_laden: prismic.RichTextField;
}

/**
 * Default variation for BookList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BookList*
 */
type BookListSliceVariation = BookListSliceDefault;

/**
 * BookList Shared Slice
 *
 * - **API ID**: `book_list`
 * - **Description**: BookList
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookListSlice = prismic.SharedSlice<
  "book_list",
  BookListSliceVariation
>;

/**
 * Item in *BookResults → Default → Primary → book*
 */
export interface BookResultsSliceDefaultPrimaryBookItem {
  /**
   * title field in *BookResults → Default → Primary → book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.book[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * author field in *BookResults → Default → Primary → book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.book[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * cover_url field in *BookResults → Default → Primary → book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.book[].cover_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cover_url: prismic.KeyTextField;
}

/**
 * Primary content in *BookResults → Default → Primary*
 */
export interface BookResultsSliceDefaultPrimary {
  /**
   * heading field in *BookResults → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * formatzahl field in *BookResults → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.formatzahl
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  formatzahl: prismic.RichTextField;

  /**
   * book field in *BookResults → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book_results.default.primary.book[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  book: prismic.GroupField<Simplify<BookResultsSliceDefaultPrimaryBookItem>>;
}

/**
 * Default variation for BookResults Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookResultsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BookResultsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BookResults*
 */
type BookResultsSliceVariation = BookResultsSliceDefault;

/**
 * BookResults Shared Slice
 *
 * - **API ID**: `book_results`
 * - **Description**: BookResults
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BookResultsSlice = prismic.SharedSlice<
  "book_results",
  BookResultsSliceVariation
>;

/**
 * Item in *Detail → Default → Primary → Formate*
 */
export interface DetailSliceDefaultPrimaryFormateItem {
  /**
   * Format field in *Detail → Default → Primary → Formate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.formate[].format
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  format: prismic.KeyTextField;
}

/**
 * Item in *Detail → Default → Primary → Kategorien*
 */
export interface DetailSliceDefaultPrimaryKategorienItem {
  /**
   * Label field in *Detail → Default → Primary → Kategorien*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.kategorien[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Detail → Default → Primary*
 */
export interface DetailSliceDefaultPrimary {
  /**
   * Cover field in *Detail → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.cover
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover: prismic.ImageField<never>;

  /**
   * Title field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Author field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Description field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Formate field in *Detail → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.formate[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  formate: prismic.GroupField<Simplify<DetailSliceDefaultPrimaryFormateItem>>;

  /**
   * Kategorien field in *Detail → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.kategorien[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  kategorien: prismic.GroupField<
    Simplify<DetailSliceDefaultPrimaryKategorienItem>
  >;

  /**
   * Beschreibung field in *Detail → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.default.primary.beschreibung
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  beschreibung: prismic.RichTextField;
}

/**
 * Default variation for Detail Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetailSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Detail*
 */
type DetailSliceVariation = DetailSliceDefault;

/**
 * Detail Shared Slice
 *
 * - **API ID**: `detail`
 * - **Description**: Detail
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailSlice = prismic.SharedSlice<"detail", DetailSliceVariation>;

/**
 * Item in *Detailslice → Default → Primary → kategorien*
 */
export interface DetailsliceSliceDefaultPrimaryKategorienItem {
  /**
   * label field in *Detailslice → Default → Primary → kategorien*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.kategorien[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Detailslice → Default → Primary → formate*
 */
export interface DetailsliceSliceDefaultPrimaryFormateItem {
  /**
   * format field in *Detailslice → Default → Primary → formate*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.formate[].format
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  format: prismic.KeyTextField;
}

/**
 * Primary content in *Detailslice → Default → Primary*
 */
export interface DetailsliceSliceDefaultPrimary {
  /**
   * kategorien field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.kategorien[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  kategorien: prismic.GroupField<
    Simplify<DetailsliceSliceDefaultPrimaryKategorienItem>
  >;

  /**
   * formate field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.formate[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  formate: prismic.GroupField<
    Simplify<DetailsliceSliceDefaultPrimaryFormateItem>
  >;

  /**
   * beschreibung field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.beschreibung
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  beschreibung: prismic.RichTextField;

  /**
   * author field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * title field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * cover_url field in *Detailslice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detailslice.default.primary.cover_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cover_url: prismic.KeyTextField;
}

/**
 * Default variation for Detailslice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailsliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DetailsliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Detailslice*
 */
type DetailsliceSliceVariation = DetailsliceSliceDefault;

/**
 * Detailslice Shared Slice
 *
 * - **API ID**: `detailslice`
 * - **Description**: Detailslice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DetailsliceSlice = prismic.SharedSlice<
  "detailslice",
  DetailsliceSliceVariation
>;

/**
 * Item in *Features → Default → Primary → Features*
 */
export interface FeaturesSliceDefaultPrimaryFeaturesItem {
  /**
   * Icon field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: calendar
   * - **API ID Path**: features.default.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "calendar" | "bargraph" | "clover" | "hourglass",
    "filled"
  >;

  /**
   * Title field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Features → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Features → Default → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Heading field in *Features → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Features field in *Features → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<FeaturesSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Horizontal → Primary*
 */
export interface HeroSliceHorizontalPrimary {
  /**
   * Heading field in *Hero → Horizontal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.horizontal.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Horizontal → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.horizontal.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Button Text field in *Hero → Horizontal → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.horizontal.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Horizontal → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.horizontal.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *Hero → Horizontal → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.horizontal.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Horizontal variation for Hero Slice
 *
 * - **API ID**: `horizontal`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceHorizontal = prismic.SharedSliceVariation<
  "horizontal",
  Simplify<HeroSliceHorizontalPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault | HeroSliceHorizontal;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Impressum → Default → Primary*
 */
export interface ImpressumSliceDefaultPrimary {
  /**
   * Heading field in *Impressum → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Impressum → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impressum.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Impressum Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpressumSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpressumSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impressum*
 */
type ImpressumSliceVariation = ImpressumSliceDefault;

/**
 * Impressum Shared Slice
 *
 * - **API ID**: `impressum`
 * - **Description**: Impressum
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpressumSlice = prismic.SharedSlice<
  "impressum",
  ImpressumSliceVariation
>;

/**
 * Primary content in *Welcome → Default → Primary*
 */
export interface WelcomeSliceDefaultPrimary {
  /**
   * Background_image field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Heading field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Welcome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for Welcome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WelcomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Welcome*
 */
type WelcomeSliceVariation = WelcomeSliceDefault;

/**
 * Welcome Shared Slice
 *
 * - **API ID**: `welcome`
 * - **Description**: Welcome
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WelcomeSlice = prismic.SharedSlice<
  "welcome",
  WelcomeSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BookDocument,
      BookDocumentData,
      BookDocumentDataFormatItem,
      BookDocumentDataCategoriesItem,
      BookDocumentDataSlicesSlice,
      FilternavDocument,
      FilternavDocumentData,
      FilternavDocumentDataFormatItem,
      FilternavDocumentDataThemenItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SearchresultsDocument,
      SearchresultsDocumentData,
      SearchresultsDocumentDataBookItem,
      SearchresultsDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      BookListSlice,
      BookListSliceDefaultPrimaryContentItem,
      BookListSliceDefaultPrimaryContent2Item,
      BookListSliceDefaultPrimary,
      BookListSliceVariation,
      BookListSliceDefault,
      BookResultsSlice,
      BookResultsSliceDefaultPrimaryBookItem,
      BookResultsSliceDefaultPrimary,
      BookResultsSliceVariation,
      BookResultsSliceDefault,
      DetailSlice,
      DetailSliceDefaultPrimaryFormateItem,
      DetailSliceDefaultPrimaryKategorienItem,
      DetailSliceDefaultPrimary,
      DetailSliceVariation,
      DetailSliceDefault,
      DetailsliceSlice,
      DetailsliceSliceDefaultPrimaryKategorienItem,
      DetailsliceSliceDefaultPrimaryFormateItem,
      DetailsliceSliceDefaultPrimary,
      DetailsliceSliceVariation,
      DetailsliceSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimaryFeaturesItem,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHorizontalPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHorizontal,
      ImpressumSlice,
      ImpressumSliceDefaultPrimary,
      ImpressumSliceVariation,
      ImpressumSliceDefault,
      WelcomeSlice,
      WelcomeSliceDefaultPrimary,
      WelcomeSliceVariation,
      WelcomeSliceDefault,
    };
  }
}
