// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  about: defineAsyncComponent(() => import("./About/index.vue")),
  book_list: defineAsyncComponent(() => import("./BookList/index.vue")),
  book_results: defineAsyncComponent(() => import("./BookResults/index.vue")),
  detail: defineAsyncComponent(() => import("./Detail/index.vue")),
  detailslice: defineAsyncComponent(() => import("./Detailslice/index.vue")),
  features: defineAsyncComponent(() => import("./Features/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  impressum: defineAsyncComponent(() => import("./Impressum/index.vue")),
  welcome: defineAsyncComponent(() => import("./Welcome/index.vue")),
});
